import { expect, test } from "@playwright/test"
import { appUrl, ids, installMockApi } from "./mock-api.js"

test("administrator signs in, inspects core state, and stops signer authorization", async ({ page }) => {
  const api = await installMockApi(page, "admin", false)
  await page.goto(appUrl.admin)
  await expect(page.getByRole("heading", { name: "Sign in to administer the clearinghouse" })).toBeVisible()
  await page.getByLabel("Administrator email address").fill("admin@example.test")
  await page.getByRole("button", { name: "Send administrator sign-in code" }).click()
  await page.getByLabel("Administrator email address").nth(1).fill("admin@example.test")
  await page.getByLabel("Six-digit sign-in code").fill("123456")
  await page.getByRole("button", { name: "Sign in as administrator" }).click()
  await expect(page.getByRole("heading", { name: "Clearinghouse overview" })).toBeVisible()
  await expect(page.getByText("20 wei", { exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Help: signer-reported cost" }).click()
  await expect(page.getByRole("note")).toBeVisible()
  await expect(page.locator("och-help-tip").first()).toContainText("fee reported by signer metering")
  await page.keyboard.press("Escape")
  await expect(page.getByRole("note")).toBeHidden()
  await page.getByLabel("Currency denomination").selectOption("eth")
  await expect(page.getByText("0.00000000000000002 ETH", { exact: true })).toBeVisible()
  await expect(page.getByText("(20 wei exact)", { exact: true })).toBeVisible()
  await page.getByRole("link", { name: "Users & accounts" }).click()
  await expect(page.getByText("member@example.test", { exact: true })).toBeVisible()
  await page.getByRole("link", { name: "Operations" }).click()
  await page.getByLabel("Reason for pausing signer authorization").fill("maintenance")
  await page.getByRole("button", { name: "Pause signer authorization" }).click()
  await expect(page.getByText("Signer authorization paused.")).toBeVisible()
  expect(api.requests.some((request) => request.method() === "PUT" && new URL(request.url()).pathname === "/v1/admin/global-stop")).toBe(true)
})

test("account user signs in and completes discovery, workload, and usage workflows", async ({ page }) => {
  const api = await installMockApi(page, "user", false)
  await page.goto(appUrl.user)
  await page.getByLabel("Account email address", { exact: true }).first().fill("member@example.test")
  await page.getByRole("button", { name: "Email a one-time code" }).click()
  await page.getByLabel("Account email address", { exact: true }).nth(1).fill("member@example.test")
  await page.getByLabel("Six-digit sign-in code").fill("123456")
  await page.getByRole("button", { name: "Verify code and sign in" }).click()
  await expect(page.getByRole("heading", { name: "Clearinghouse overview" })).toBeVisible()
  await page.getByRole("button", { name: "Help: signer-reported cost" }).click()
  await expect(page.getByRole("note")).toBeVisible()
  await expect(page.locator("och-help-tip").first()).toContainText("fee reported by signer metering")
  await page.keyboard.press("Escape")
  await page.getByLabel("Currency denomination").selectOption("eth")
  await expect(page.getByText("0.00000000000000002 ETH", { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel("Currency denomination")).toHaveValue("eth")
  await page.getByRole("link", { name: "Network", exact: true }).click()
  await expect(page.getByText("live-video-to-video", { exact: true })).toBeVisible()
  await page.getByRole("link", { name: "Cost estimator" }).click()
  await page.getByLabel("Output width in pixels").fill("10")
  await page.getByLabel("Output height in pixels").fill("10")
  await page.getByLabel("Frames or images per execution").fill("2")
  await expect(page.getByText("0.0000000000000004 ETH", { exact: true })).toBeVisible()
  await page.getByLabel("Job reference (optional)").fill("sdk-job-1")
  await page.getByLabel("Maximum spend (ETH, optional)").fill("0.0000000000000005")
  await page.getByRole("button", { name: "Create workload access at this rate" }).click()
  const workloadToken = page.getByRole("dialog", { name: "Workload SDK token created" })
  await expect(workloadToken).toContainText("only to livepeer-python-gateway for this quoted workload")
  await expect(workloadToken).toContainText("expires with the workload")
  await expect(workloadToken).toContainText("cannot be shown again")
  await expect(workloadToken).toContainText("sdk-token")
  await page.getByRole("button", { name: "Close after saving this secret" }).click()
  await page.getByRole("link", { name: "Workloads", exact: true }).click()
  await expect(page.getByText("Access expires").first()).toBeVisible()
  await page.getByRole("link", { name: "Account API credentials", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Account API credentials", level: 2 })).toBeVisible()
  await expect(page.getByText("authorize account-scoped Clearinghouse requests")).toBeVisible()
  await page.getByLabel("Credential name").fill("Gateway automation")
  await page.getByRole("button", { name: "Create account API credential" }).click()
  const accountCredential = page.getByRole("dialog", { name: "Account API credential created" })
  await expect(accountCredential).toContainText("och_live_")
  await expect(accountCredential).toContainText("remains valid until you revoke it")
  await expect(accountCredential).toContainText("cannot be shown again")
  await page.getByRole("button", { name: "Close after saving this secret" }).click()
  await page.getByRole("link", { name: "Usage & cost" }).click()
  await expect(page.getByText(ids.workload, { exact: true })).toBeVisible()
  await expect(page.getByText("0.00000000000000002 ETH", { exact: true }).first()).toBeVisible()
  const create = api.requests.find((request) => request.method() === "POST" && new URL(request.url()).pathname === "/v1/workloads")
  expect(create).toBeDefined()
  expect(create?.postDataJSON()).toMatchObject({ max_spend_wei: "500" })
  await expect(page.getByText("0.00000000000000007 ETH", { exact: true })).toBeVisible()
})
