import { expect, test } from "@playwright/test"
import { appUrl, ids, installMockApi } from "./mock-api.js"

test("administrator signs in, inspects core state, and stops signer authorization", async ({ page }) => {
  const api = await installMockApi(page, "admin", false)
  await page.goto(appUrl.admin)
  await expect(page.getByRole("heading", { name: "Sign in to administer the clearinghouse" })).toBeVisible()
  await page.getByLabel("Email address").fill("admin@example.test")
  await page.getByRole("button", { name: "Email a one-time code" }).click()
  await page.getByLabel("Email address").nth(1).fill("admin@example.test")
  await page.getByLabel("One-time code").fill("123456")
  await page.getByRole("button", { name: "Verify code" }).click()
  await expect(page.getByRole("heading", { name: "Clearinghouse overview" })).toBeVisible()
  await expect(page.getByText("20 wei", { exact: true })).toBeVisible()
  await page.getByLabel("Currency denomination").selectOption("eth")
  await expect(page.getByText("0.00000000000000002 ETH", { exact: true })).toBeVisible()
  await expect(page.getByText("(20 wei exact)", { exact: true })).toBeVisible()
  await page.getByRole("link", { name: "Users & accounts" }).click()
  await expect(page.getByText("member@example.test", { exact: true })).toBeVisible()
  await page.getByRole("link", { name: "Operations" }).click()
  await page.getByLabel("Audit reason").fill("maintenance")
  await page.getByRole("button", { name: "Stop authorization" }).click()
  await expect(page.getByText("Signer authorization stopped.")).toBeVisible()
  expect(api.requests.some((request) => request.method() === "PUT" && new URL(request.url()).pathname === "/v1/admin/global-stop")).toBe(true)
})

test("account user signs in and completes discovery, workload, and usage workflows", async ({ page }) => {
  const api = await installMockApi(page, "user", false)
  await page.goto(appUrl.user)
  await page.getByLabel("Email address", { exact: true }).first().fill("member@example.test")
  await page.getByRole("button", { name: "Send one-time code" }).click()
  await page.getByLabel("Email address", { exact: true }).nth(1).fill("member@example.test")
  await page.getByLabel("Six-digit code").fill("123456")
  await page.getByRole("button", { name: "Verify and sign in" }).click()
  await expect(page.getByRole("heading", { name: "Clearinghouse overview" })).toBeVisible()
  await page.getByLabel("Currency denomination").selectOption("eth")
  await expect(page.getByText("0.00000000000000002 ETH", { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel("Currency denomination")).toHaveValue("eth")
  await page.getByRole("link", { name: "Network" }).click()
  await expect(page.getByText("live-video-to-video", { exact: true })).toBeVisible()
  await page.getByRole("link", { name: "Cost estimator" }).click()
  await page.getByLabel("Output width in pixels").fill("10")
  await page.getByLabel("Output height in pixels").fill("10")
  await page.getByLabel("Frames or images per execution").fill("2")
  await expect(page.getByText("0.0000000000000004 ETH", { exact: true })).toBeVisible()
  await page.getByLabel("Your job reference (optional)").fill("sdk-job-1")
  await page.getByRole("button", { name: "Create Python SDK token at this rate" }).click()
  await expect(page.getByRole("dialog", { name: "Python SDK token created" })).toContainText("sdk-token")
  await page.getByRole("button", { name: "I saved it" }).click()
  await page.getByRole("link", { name: "Workloads" }).click()
  await expect(page.getByText("Access ends")).toBeVisible()
  await page.getByRole("link", { name: "Usage & cost" }).click()
  await expect(page.getByText(ids.workload, { exact: true })).toBeVisible()
  await expect(page.getByText("0.00000000000000002 ETH", { exact: true }).first()).toBeVisible()
  expect(api.requests.some((request) => request.method() === "POST" && new URL(request.url()).pathname === "/v1/workloads")).toBe(true)
})
